// Code generated by "stringer -type=Activation"; DO NOT EDIT

package state

import "fmt"

const _Activation_name = "InactiveActivatingActiveFailed"

var _Activation_index = [...]uint8{0, 8, 18, 24, 30}

func (i Activation) String() string {
	if i < 0 || i >= Activation(len(_Activation_index)-1) {
		return fmt.Sprintf("Activation(%d)", i)
	}
	return _Activation_name[_Activation_index[i]:_Activation_index[i+1]]
}
