// Code generated by "stringer -type=Active"; DO NOT EDIT

package state

import "fmt"

const _Active_name = "UnitActiveUnitReloadingUnitInactiveUnitFailedUnitActivatingUnitDeactivating"

var _Active_index = [...]uint8{0, 10, 23, 35, 45, 59, 75}

func (i Active) String() string {
	if i < 0 || i >= Active(len(_Active_index)-1) {
		return fmt.Sprintf("Active(%d)", i)
	}
	return _Active_name[_Active_index[i]:_Active_index[i+1]]
}
