// Code generated by "stringer -type=Enable"; DO NOT EDIT

package state

import "fmt"

const _Enable_name = "DisabledStaticIndirectEnabled"

var _Enable_index = [...]uint8{0, 8, 14, 22, 29}

func (i Enable) String() string {
	if i < 0 || i >= Enable(len(_Enable_index)-1) {
		return fmt.Sprintf("Enable(%d)", i)
	}
	return _Enable_name[_Enable_index[i]:_Enable_index[i+1]]
}
