// Code generated by "stringer -type=Load"; DO NOT EDIT

package state

import "fmt"

const _Load_name = "LoadedError"

var _Load_index = [...]uint8{0, 6, 11}

func (i Load) String() string {
	if i < 0 || i >= Load(len(_Load_index)-1) {
		return fmt.Sprintf("Load(%d)", i)
	}
	return _Load_name[_Load_index[i]:_Load_index[i+1]]
}
