// Code generated by "stringer -type=Mount"; DO NOT EDIT

package state

import "fmt"

const _Mount_name = "MountDeadMountMountingMountMountingDoneMountMountedMountRemountingMountUnmountingMountMountingSigtermMountMountingSigkillMountRemountingSigtermMountRemountingSigkillMountUnmountingSigtermMountUnmountingSigkillMountFailed"

var _Mount_index = [...]uint8{0, 9, 22, 39, 51, 66, 81, 101, 121, 143, 165, 187, 209, 220}

func (i Mount) String() string {
	if i < 0 || i >= Mount(len(_Mount_index)-1) {
		return fmt.Sprintf("Mount(%d)", i)
	}
	return _Mount_name[_Mount_index[i]:_Mount_index[i+1]]
}
