// Code generated by "stringer -type=Sub"; DO NOT EDIT

package state

import "fmt"

const _Sub_name = "UnavailableMountedMounting"

var _Sub_index = [...]uint8{0, 11, 18, 26}

func (i Sub) String() string {
	if i < 0 || i >= Sub(len(_Sub_index)-1) {
		return fmt.Sprintf("Sub(%d)", i)
	}
	return _Sub_name[_Sub_index[i]:_Sub_index[i+1]]
}
