// Code generated by "stringer -type=System"; DO NOT EDIT

package state

import "fmt"

const _System_name = "SomethingDegraded"

var _System_index = [...]uint8{0, 9, 17}

func (i System) String() string {
	if i < 0 || i >= System(len(_System_index)-1) {
		return fmt.Sprintf("System(%d)", i)
	}
	return _System_name[_System_index[i]:_System_index[i+1]]
}
