// Code generated by "stringer -type=ActivationState"; DO NOT EDIT

package unit

import "fmt"

const _ActivationState_name = "InactiveActivatingActiveFailed"

var _ActivationState_index = [...]uint8{0, 8, 18, 24, 30}

func (i ActivationState) String() string {
	if i < 0 || i >= ActivationState(len(_ActivationState_index)-1) {
		return fmt.Sprintf("ActivationState(%d)", i)
	}
	return _ActivationState_name[_ActivationState_index[i]:_ActivationState_index[i+1]]
}
