// Code generated by "stringer -type=EnableState"; DO NOT EDIT

package unit

import "fmt"

const _EnableState_name = "DisabledStaticIndirectEnabled"

var _EnableState_index = [...]uint8{0, 8, 14, 22, 29}

func (i EnableState) String() string {
	if i < 0 || i >= EnableState(len(_EnableState_index)-1) {
		return fmt.Sprintf("EnableState(%d)", i)
	}
	return _EnableState_name[_EnableState_index[i]:_EnableState_index[i+1]]
}
