// Code generated by "stringer -type=LoadState"; DO NOT EDIT

package unit

import "fmt"

const _LoadState_name = "LoadedError"

var _LoadState_index = [...]uint8{0, 6, 11}

func (i LoadState) String() string {
	if i < 0 || i >= LoadState(len(_LoadState_index)-1) {
		return fmt.Sprintf("LoadState(%d)", i)
	}
	return _LoadState_name[_LoadState_index[i]:_LoadState_index[i+1]]
}
