// Code generated by "stringer -type=state"; DO NOT EDIT

package unit

import "fmt"

const _state_name = "StaticIndirectDisabledEnabled"

var _state_index = [...]uint8{0, 6, 14, 22, 29}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return fmt.Sprintf("state(%d)", i)
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
