// Code generated by "stringer -type EnableState,LoadState,ActivationState unit.go"; DO NOT EDIT

package unit

import "fmt"

const _EnableState_name = "DisabledStaticIndirectEnabled"

var _EnableState_index = [...]uint8{0, 8, 14, 22, 29}

func (i EnableState) String() string {
	if i < 0 || i >= EnableState(len(_EnableState_index)-1) {
		return fmt.Sprintf("EnableState(%d)", i)
	}
	return _EnableState_name[_EnableState_index[i]:_EnableState_index[i+1]]
}

const _LoadState_name = "LoadedError"

var _LoadState_index = [...]uint8{0, 6, 11}

func (i LoadState) String() string {
	if i < 0 || i >= LoadState(len(_LoadState_index)-1) {
		return fmt.Sprintf("LoadState(%d)", i)
	}
	return _LoadState_name[_LoadState_index[i]:_LoadState_index[i+1]]
}

const _ActivationState_name = "InactiveActivatingActiveFailed"

var _ActivationState_index = [...]uint8{0, 8, 18, 24, 30}

func (i ActivationState) String() string {
	if i < 0 || i >= ActivationState(len(_ActivationState_index)-1) {
		return fmt.Sprintf("ActivationState(%d)", i)
	}
	return _ActivationState_name[_ActivationState_index[i]:_ActivationState_index[i+1]]
}
